# Generated by Django 4.1.6 on 2023-02-11 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "invitations",
            "0003_alter_invitation_company_alter_invitation_created_by_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="active",
        ),
    ]
