# Generated by Django 4.1.6 on 2023-02-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_companyrole_alter_company_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyrole",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
