# Generated by Django 4.1.6 on 2023-02-09 22:41

import apps.companies.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_companyrole_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.companies.models.content_file_name
            ),
        ),
    ]
