# Generated by Django 4.1.6 on 2023-02-09 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_alter_company_logo"),
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company_role",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companyrole",
            ),
        ),
    ]
