# Generated by Django 4.1.6 on 2023-02-12 00:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="active",
        ),
    ]
